### ISSUE TITLE
Character Entity Reference

### ISSUE THREAD

**Issue by jim-rosales** [darthrox/colmaracademy#2]
It's best practice when adding symbols such as the ampersand and copyright to add them via their [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

For example, in this case, you'd replace `&` with `&amp;`

https://github.com/darthrox/colmaracademy/blob/1f8501c9ada7d285335dbdfacd0b8e231b98b7f7/index.html#L76

**Comment by darthrox** [comment]
Thanks, forgot to review the given text, my fault to just paste and copy them :-)
