### ISSUE TITLE
Variable Use

### ISSUE THREAD

**Issue by jim-rosales** [darthrox/colmaracademy#5]
Consider making use of [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables); it seems you can take advantage of them for all the colors you use. Variables are a great tool that allow you to increase the maintainability and readability of your stylesheet. 

https://github.com/darthrox/colmaracademy/blob/1f8501c9ada7d285335dbdfacd0b8e231b98b7f7/resources/css/style.css#L4-L10

**Comment by darthrox** [comment]
Thanks for this, this will be a great improvement !
