### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [darthrox/colmaracademy#6]
Grade: Exceeds Expectations

Summary:
Gerret, incredible job on your capstone project! The various transitions and hover effects you added were a nice touch to the project. You also did a fantastic job making sure your files were readable considering you added comments to both your HTML and CSS file. 

One thing to consider is going over this [style guide](https://github.com/airbnb/css) to improve the readability of your CSS file further. A couple of the guidelines mentioned in the guide is to have one selector per line for included rules, as well as have a line of whitespace between each rule.

**Comment by darthrox** [comment]
Hello and thank you for this very detailed and useful review, this helps a lot to code better, greetings Gerret.
